<div class="control-grid full-width pb-0">
	<span>
		<!-- todo tkb link -->
		<?php echo esc_html__( 'Video events can be enabled and reported on through your reporting dashboards.', 'thrive-cb' ); ?>
		<a class="blue-text" href="https://help.thrivethemes.com/en/articles/5448023-enabling-lazy-loading-for-video-elements" target="_blank">
			<?php echo __( 'Read more', 'thrive-cb' ) ?>
		</a>
	</span>
</div>
