<div class="tva-drip-content">
	<div class="tva-opt tva-drip-assessment">
		<div class="tva-label"><?php esc_html_e( 'Assessment to be passed', 'thrive-apprentice' ); ?></div>
		<select id="tva-drip-assessment-dropdown" data-bind="object_id"></select>
		<div class="tva-label mt-20"><?php esc_html_e( 'Unlock when', 'thrive-apprentice' ); ?></div>
		<select id="tva-drip-assessment-when" data-bind="when">
			<option value="pass"><?php esc_html_e( 'Assessment passed', 'thrive-apprentice' ); ?></option>
			<option value="submit"><?php esc_html_e( 'Assessment submitted', 'thrive-apprentice' ); ?></option>
			<option value="fail"><?php esc_html_e( 'Assessment failed', 'thrive-apprentice' ); ?></option>
		</select>
	</div>
</div>
