<div class="tva-assessment-tqb-header">
	<span class="mr-30"><?php _e( 'Start', 'thrive-apprentice' ) ?><span class="tva-assessment-tqb-dark"><#- date_started #></span></span>
	<span><?php _e( 'Completed', 'thrive-apprentice' ) ?><span class="tva-assessment-tqb-dark"><#- date_finished #></span></span>
	<span class="tva-assessment-tqb-time mr-30">
		<?php _e( 'Time', 'thrive-apprentice' ) ?>
		<span class="tva-assessment-tqb-dark"><#- completionTime #><?php _e( 'min', 'thrive-apprentice' ) ?></span>
	</span>
	<span><?php _e( 'Tries', 'thrive-apprentice' ) ?><span class="tva-assessment-tqb-dark"><#- nb_of_tries #></span></span>
	<div class="tva-assessment-tqb-title"><h3><#- quiz_title #></h3></div>
</div>
