<?php
/**
 * Thrive Themes - https://thrivethemes.com
 *
 * @package thrive-apprentice
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Silence is golden!
}
?>
<div class="info-link mt-10">
	<span class="info-text orange">
		<div><strong><?php echo __( 'To display your assessments to your students you may need to:', 'thrive-apprentice' ); ?></strong></div>
		<div><?php echo __( '1. Rerun the Apprentice template wizard here and update the Course overview, Module and Sidebars templates', 'thrive-apprentice' ); ?></div>
		<div><?php echo __( '2. Reapply your lesson list (sidebar) template', 'thrive-apprentice' ); ?></div>
		<div><?php echo __( 'OR', 'thrive-apprentice' ); ?></div>
		<div><?php echo __( '3. if you have heavily customized lesson lists you can choose to manually style the assessment items in each state', 'thrive-apprentice' ); ?></div>
		<a href="https://help.thrivethemes.com/en/articles/8095758-how-to-enable-assessments-in-thrive-apprentice" target="_blank" rel="noopener"><?php echo __( 'Click here to learn more', 'thrive-apprentice' ); ?></a>
	</span>
</div>
