<div class="tvd-modal-content">
	<div class="tva-flex tva-space-around">
		<span class="tva-assessments-help-title"><?php echo __( 'Introducing Assessments', 'thrive-apprentice' ) ?></span>
	</div>
	<div class="tva-flex tva-space-around mt-20">
		<iframe width="498" height="280" type="text/html" title="Introducing Assessments" src="https://www.youtube.com/embed/j0WL0lKn1ss?autoplay=0&fs=0&iv_load_policy=3&showinfo=0&rel=0&cc_load_policy=0&start=0&end=0"></iframe>
	</div>
	<div class="tva-ah-450">
		<span class="tva-flex tva-text-center mt-20 mb-20 tva-assessments-help-text"><?php echo __( 'With the new Assessment feature, you can evaluate the progress of your students and gain insight into what students understand.', 'thrive-apprentice' ) ?></span>
	</div>
	<div class="tva-flex tva-space-around">
		<div class="tva-flex">
			<a rel="noopener" href="https://help.thrivethemes.com/en/articles/8095758-how-to-enable-assessments-in-thrive-apprentice" target="_blank" class="tva-btn mr-25 tva-btn-ghost"><?php echo __( 'Read the full guide', 'thrive-apprentice' ) ?></a>
			<a href="javascript:void(0);" class="tva-btn tva-btn-blue pl-30 pr-30 tvd-modal-close"><?php echo __( 'Let\'s go!', 'thrive-apprentice' ) ?></a>
		</div>
	</div>
</div>
