<div class="tvd-modal-content">
	<h3 class="tvd-modal-title">
		<?php echo esc_html__( 'Archive this course?', 'thrive-apprentice' ); ?>
	</h3>
	<p class="mb-0">
		<?php echo esc_html__( 'Archiving a course will remove it from publicly accessible course lists. However, it will still be available to customers who have already been granted access to the course.', 'thrive-apprentice' ); ?>
	</p>
</div>
<div class="tva-modal-footer-outer">
	<button type="button" class="tva-modal-btn tvd-modal-close click" data-fn="cancel"><?php echo esc_html__( 'Cancel', 'thrive-apprentice' ); ?></button>
	<button type="button" class="tva-modal-btn tva-modal-btn-blue tvd-modal-save click" data-fn="confirm"><?php echo esc_html__( 'Yes, archive this course', 'thrive-apprentice' ); ?></button>
</div>
