<?php

/**
 * Thrive Themes - https://thrivethemes.com
 *
 * @package thrive-apprentice
 */

use TVA\Architect\Assessment\Main;
use TVA\Assessments\Grading\Base as Grading_Base;
use TVA\Assessments\Grading\Category as Grading_Category;
use function TVA\TQB\tva_tqb_integration;

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Silence is golden!
}
$has_tqb          = tva_tqb_integration()->is_quiz_builder_active();
$has_upload_setup = tva_assessment_settings()->can_upload_assessments();
?>
<div class="tva-modal-step" id="tvd-parent-selection-step">
	<div class="tvd-modal-content tva-no-after">
		<h3 class="tvd-modal-title"><?php echo __( 'Add course content', 'thrive-apprentice' ) ?></h3>
		<p id="tva-item-description"></p>
		<select id="tva-parent-target"></select>
	</div>
	<div class="tva-modal-footer-outer">
		<button type="button" class="tva-modal-btn tvd-modal-close"><?php echo esc_html__( 'Close', 'thrive-apprentice' ); ?></button>
		<button type="button" class="tva-modal-btn tva-modal-btn-green click" data-fn="setParent"><?php echo esc_html__( 'Continue', 'thrive-apprentice' ); ?></button>
	</div>
</div>

<div class="tva-modal-step tva-assessment-modal-step">
	<div class="tvd-modal-content">
		<h3 class="tvd-modal-title mb-20"><?php echo __( 'Create an assessment', 'thrive-apprentice' ) ?></h3>
		<# if(!TVA.skins.getActiveSkin().isAssessmentReady()){ #>
		<div class="tva-container-notice tva-container-notice-red mt-10 mb-20 pl-10">
			<span>
				<?php echo __( 'To enable assessments, you will need to reload the lesson list templates inside of Thrive Apprentice. This is necessary to add the assessment option for your students.', 'thrive-apprentice' ); ?>
				<a href="https://help.thrivethemes.com/en/articles/8176663-how-to-refresh-templates-in-thrive-apprentice-after-adding-assessments" rel="noopener" target="_blank"><?php echo __( 'Click here to learn more.', 'thrive-apprentice' ); ?></a>
			</span>
		</div>
		<# } #>
		<div class="tva-blue-bubble-info-text tva-bb-assessment mb-5">
			<p class="tva-bb-question-box"><?php esc_html_e( 'How do you want your students to submit the Assessment?', 'thrive-apprentice' ); ?>
		</div>
		<div class="tva-assessment-type-cards mt-20">
			<div class="<?php echo ! $has_tqb ? 'tva-assessment-type-inactive ' : ' '; ?>tva-assessment-type click" data-fn="<?php echo $has_tqb ? 'setType' : ''; ?>" data-type="<?php echo Main::TYPE_QUIZ; ?>">
				<?php if ( ! $has_tqb ) : ?>
					<span class="tva-assessment-inactive"><?php tva_get_svg_icon( 'lock-alt' ); ?><?php echo __( 'Not activated', 'thrive-apprentice' ); ?></span>
				<?php endif; ?>
				<div class="tva-assessment-circle">
					<img alt="tqb-icon" src="<?php echo TVA_Const::plugin_url( 'admin/includes/assets/img/assessments/tqb@2x.webp' ); ?>" width="55">
				</div>
				<h4>Take a Quiz</h4>
				<p><?php echo __( 'Test your students with a quiz built in the Thrive Quiz Builder.', 'thrive-apprentice' ); ?></p>
				<?php if ( ! $has_tqb ) : ?>
					<button class="pl-20 pr-20 tva-empty-btn tva-empty-btn-green click" data-fn="goToLink" data-url="<?php echo esc_url( admin_url( 'admin.php?page=thrive_product_manager' ) ); ?>"><?php echo __( 'Get access now', 'thrive-apprentice' ); ?></button>
				<?php endif; ?>
			</div>
			<div class="<?php echo ! $has_upload_setup ? 'tva-assessment-type-inactive ' : ' '; ?>tva-assessment-type click" data-fn="<?php echo $has_upload_setup ? 'setType' : ''; ?>" data-type="<?php echo Main::TYPE_UPLOAD; ?>">
				<?php if ( ! $has_upload_setup ) : ?>
					<span class="tva-assessment-inactive"><?php tva_get_svg_icon( 'cog' ); ?><?php echo __( 'Not set up', 'thrive-apprentice' ); ?></span>
				<?php endif; ?>
				<div class="tva-assessment-circle">
					<img alt="upload-icon" src="<?php echo TVA_Const::plugin_url( 'admin/includes/assets/img/assessments/upload@2x.webp' ); ?>" height="50">
				</div>
				<h4>Upload an Assessment</h4>
				<p><?php echo __( 'Let your students upload their assessment as a PDF file, .docx, etc', 'thrive-apprentice' ); ?></p>
				<?php if ( ! $has_upload_setup ) : ?>
					<button class="tva-empty-btn tva-empty-close click" data-fn="goToLink" data-url="<?php echo esc_url( admin_url( 'admin.php?page=thrive_apprentice#settings/assessment-settings' ) ) ?>"><?php echo __( 'Set up now', 'thrive-apprentice' ); ?></button>
				<?php endif; ?>
			</div>
			<div class="tva-assessment-type click" data-fn="setType" data-type="<?php echo Main::TYPE_YOUTUBE_LINK; ?>">
				<div class="tva-assessment-circle">
					<img alt="youtube-icon" src="<?php echo TVA_Const::plugin_url( 'admin/includes/assets/img/assessments/youtube@2x.webp' ); ?>" width="53">
				</div>
				<h4>Share YouTube Link</h4>
				<p><?php echo __( 'Ask your students to share a YouTube link to the uploaded video.', 'thrive-apprentice' ); ?></p>
			</div>
			<div class="tva-assessment-type click" data-fn="setType" data-type="<?php echo Main::TYPE_EXTERNAL_LINK; ?>">
				<div class="tva-assessment-circle">
					<img alt="external-icon" src="<?php echo TVA_Const::plugin_url( 'admin/includes/assets/img/assessments/external@2x.webp' ); ?>" height="43">
				</div>
				<h4>External Link</h4>
				<p><?php echo __( 'Accept assessment submissions in the form of external links.', 'thrive-apprentice' ); ?></p>
			</div>
		</div>
		<div class="tva-modal-footer-inner mt-40 tva-flex tva-space-between">
			<button type="button" class="tva-modal-btn tvd-modal-close"><?php echo esc_html__( 'Cancel', 'thrive-apprentice' ); ?></button>
			<span class="tva-step-marker"><?php echo esc_html__( 'Step 1 of 2', 'thrive-apprentice' ); ?></span>
			<button type="button" class="tva-modal-btn tva-modal-btn-fill-green click tvd-modal-save tva-assessment-continue tva-disabled" data-fn="goToAssessmentSettings">
				<?php echo esc_html__( 'Continue', 'thrive-apprentice' ); ?>
			</button>
		</div>
	</div>
</div>

<div class="tva-modal-step tva-assessment-modal-step-two">
	<div class="tvd-modal-content">
		<h3 class="tvd-modal-title"><?php echo __( 'Assessment details', 'thrive-apprentice' ); ?></h3>
		<div class="tva-flex mb-20">
			<div class="tvd-input-field tva-flex-one mr-20">
				<input id="tva-lesson-title" data-bind="post_title" value="<#= model.get('post_title') #>" type="text" placeholder="<?php echo esc_html__( 'Assessment Title', 'thrive-apprentice' ); ?>">
				<label>&nbsp;</label>
			</div>

			<div class="ta-flex-250 tva-assessment-no-edit">
				<select name="tva-assessment-type" id="tva-assessment-type" data-bind="assessment_type">
					<?php foreach ( TVA_Assessment::$types as $type => $label ): ?>
						<option value="<?php echo $type; ?>"><?php echo $label; ?></option>
					<?php endforeach; ?>
				</select>
			</div>
		</div>
		<div class="tva-container-notice tva-container-notice-orange tva-upload-notice mb-20">
			<?php tva_get_svg_icon( 'info-circle_light' ); ?>
			<?php echo __( 'You have not configured your upload folder.', 'thrive-apprentice' ); ?> <a target="_blank" href="<?php echo esc_url( admin_url( 'admin.php?page=thrive_apprentice#settings/assessment-settings' ) ) ?>">&nbsp;<?php echo __( 'Click here', 'thrive-apprentice' ); ?> </a>
		</div>
		<div class="tva-assessment-tabs">
			<div class="tva-assessment-tabs-header">
				<div class="tva-tab click" data-fn="setTab" data-tab="options">
					<?php tva_get_svg_icon( 'balance' ); ?>
					<?php echo __( 'Assessment options', 'thrive-apprentice' ); ?>
				</div>
				<div class="tva-tab click" data-fn="setTab" data-tab="general">
					<?php tva_get_svg_icon( 'settings-icon' ); ?>
					<?php echo __( 'General', 'thrive-apprentice' ); ?>
				</div>
			</div>
			<div class="tva-modal-b-inner tva-assessment-tabs-content">
				<div class="tva-tab-content tva-tab-options">
					<div class="tva-container-notice tva-container-notice-red tva-with-submissions-notice mt-15 mb-10 tva-hide">
						<?php tva_get_svg_icon( 'triangle-exclamation_light' ); ?>
						<?php echo __( 'This assessment has received a submission and can no longer be edited.', 'thrive-apprentice' ); ?>
					</div>
					<div class="tva-assessment-options-section" data-type="upload">
						<div class="tva-flex tva-align-center mt-20">
							<h5><?php echo __( 'Upload settings', 'thrive-apprentice' ); ?></h5>
							<div class="tva-line-sep ml-15"></div>
						</div>
						<div class="tva-assessment-upload-settings tva-flex tva-assessment-no-edit">
							<div class="tva-assessment-upload-files">
								<label for="tva-assessment-max-files"><?php echo __( 'Max number of files', 'thrive-apprentice' ); ?></label>
								<input id="tva-assessment-max-files" data-bind="upload_max_files" type="number" min="1"/>
								<span>&nbsp;</span>

								<label for="tva-assessment-max-filesize" class="tva-flex tva-align-center">
									<span class="mr-20"><?php echo __( 'Max filesize', 'thrive-apprentice' ); ?></span>
									<div class="tva-flex tva-align-center tva-tooltip-parent">
										<?php tva_get_svg_icon( 'info-solid' ); ?>
										<div class="tva-custom-tooltip tva-tooltip-inherited">
											<?php esc_html_e( 'The max filesize is limited to the upload limit as set on your site. If you would like to increase this you can either adjust your PHP configuration or contact your host.', 'thrive-apprentice' ); ?>
										</div>
									</div>
								</label>
								<input id="tva-assessment-max-filesize" data-bind="upload_max_file_size" type="number" min="1" max="<?php echo esc_attr( tve_get_max_upload_size() ); ?>"/>
								<span>MB</span>
							</div>
							<div class="tva-assessment-upload-file-types">
								<span class="label"><?php echo __( 'Allowed file types', 'thrive-apprentice' ); ?></span>
								<div class="tva-assessment-file-type click" data-fn="toggleAllowedFile" data-file="documents">
									<?php tva_get_svg_icon( 'file_light' ); ?>
									<span class="tva-assessment-file-type-name"><?php echo __( 'Documents', 'thrive-apprentice' ); ?></span>
								</div>
								<div class="tva-assessment-file-type click" data-fn="toggleAllowedFile" data-file="images">
									<?php tva_get_svg_icon( 'image' ); ?>
									<span class="tva-assessment-file-type-name"><?php echo __( 'Images', 'thrive-apprentice' ); ?></span>
								</div>
								<div class="tva-assessment-file-type click" data-fn="toggleAllowedFile" data-file="zip">
									<?php tva_get_svg_icon( 'archive' ); ?>
									<span class="tva-assessment-file-type-name"><?php echo __( 'Zip archives', 'thrive-apprentice' ); ?></span>
								</div>
								<div class="tva-assessment-file-type click" data-fn="toggleAllowedFile" data-file="video">
									<?php tva_get_svg_icon( 'video' ); ?>
									<span class="tva-assessment-file-type-name"><?php echo __( 'Video files', 'thrive-apprentice' ); ?></span>
								</div>
								<div class="tva-assessment-file-type click" data-fn="toggleAllowedFile" data-file="audio">
									<?php tva_get_svg_icon( 'audio' ); ?>
									<span class="tva-assessment-file-type-name"><?php echo __( 'Audio files', 'thrive-apprentice' ); ?></span>
								</div>
								<div class="tva-assessment-file-type click" data-fn="toggleAllowedFile" data-file="custom">
									<?php tva_get_svg_icon( 'wrench' ); ?>
									<span class="tva-assessment-file-type-name"><?php echo __( 'Custom', 'thrive-apprentice' ); ?></span>
								</div>
								<input class="tva-assessment-custom-extensions" data-bind="upload_custom_extensions" type="text" placeholder="<?php echo __( 'Enter your custom file extensions ( Examples: txt, png )', 'thrive-apprentice' ); ?>"/>
							</div>
						</div>
						<div class="tva-container-notice tva-container-notice-red tva-assessment-files-notice tva-hide">
							<?php tva_get_svg_icon( 'info-circle_light' ); ?>
							<div>
								<?php echo __( 'You need at least one file type selected', 'thrive-apprentice' ); ?>
							</div>
						</div>
					</div>
					<div class="tva-assessment-options-section" data-type="tqb">
						<div class="tva-flex tva-align-center mt-20">
							<h5><?php echo __( 'Quiz source', 'thrive-apprentice' ); ?></h5>
							<div class="tva-line-sep ml-15"></div>
						</div>
						<div class="tva-assessment-quiz-container tva-flex tva-space-between tva-align-center mt-15 tva-assessment-no-edit">
							<label for="tva-assessment-quiz"><?php echo __( 'Use this quiz', 'thrive-apprentice' ); ?>:</label>
							<select id="tva-assessment-quiz" data-bind="quiz_id"></select>
						</div>
						<div class="tva-container-notice tva-container-notice-red tva-tqb-unavailable mt-10">
							<?php tva_get_svg_icon( 'info-circle_light' ); ?>
							<div>
								<?php echo __( 'Looks like the selected quiz is not available. Please check if Thrive Quiz Builder is active or if the selected quiz is published.', 'thrive-apprentice' ); ?>
								<br>
								<a href="<?php echo esc_url( admin_url( 'admin.php?page=tqb_admin_dashboard' ) ); ?>" target="_blank"><?php echo __( 'Learn more', 'thrive-apprentice' ); ?></a>
							</div>
						</div>
						<div class="tva-tqb-settings mt-10"><p><?php echo __( 'To manage your quizzes go to ', 'thrive-apprentice' ); ?><a href="<?php echo esc_url( admin_url( 'admin.php?page=tqb_admin_dashboard' ) ); ?>" target="_blank">Thrive Quiz Builder</a></p></div>
					</div>
					<div class="tva-assessment-options-section" data-type="youtube_link">
						<div class="tva-container-notice tva-container-notice-green mb-10 mt-10">
							<?php tva_get_svg_icon( 'info-circle_light' ); ?>
							<?php echo __( 'You\'ll need to use Thrive Architect to edit the page and form your students will submit.', 'thrive-apprentice' ); ?>
						</div>
					</div>
					<div class="tva-assessment-options-section" data-type="external_link">
						<div class="tva-container-notice tva-container-notice-green mb-10 mt-10">
							<?php tva_get_svg_icon( 'info-circle_light' ); ?>
							<?php echo __( 'You\'ll need to use Thrive Architect to edit the page and form your students will submit.', 'thrive-apprentice' ); ?>
						</div>
					</div>
					<div class="tva-assessment-options-grading mt-20">
						<div class="tva-flex tva-align-center">
							<h5><?php echo __( 'Grading settings', 'thrive-apprentice' ); ?></h5>
							<div class="tva-line-sep ml-15"></div>
						</div>
						<div class="tva-grading-setting tva-assessment-no-edit" data-setting="grading_method">
							<label for="tva-grading-method" class="tva-flex tva-align-center">
								<span><?php echo __( 'Grading method', 'thrive-apprentice' ); ?></span>
							</label>
							<select id="tva-grading-method" data-bind="grading_method">
								<?php foreach ( Grading_Base::$grading_methods as $method => $label ): ?>
									<option value="<?php echo $method; ?>"><?php echo $label; ?></option>
								<?php endforeach; ?>
							</select>
						</div>
						<div class="tva-grading-setting">
							<div class="tva-grading-passing tva-assessment-no-edit" data-type="percentage">
								<label for="tva-grading-passing-percentage" class="tva-flex tva-align-center">
									<span><?php echo __( 'Passing percentage', 'thrive-apprentice' ); ?></span>
								</label>
								<input id="tva-grading-passing-percentage" data-bind="passing_percentage" type="number" min="0" max="100"/>
							</div>
							<div class="tva-grading-passing tva-assessment-no-edit" data-type="score">
								<label for="tva-grading-passing-score" class="tva-flex tva-align-center">
									<span><?php echo __( 'Passing score', 'thrive-apprentice' ); ?></span>
								</label>
								<input id="tva-grading-passing-score" data-bind="passing_score" type="number" min="0"/>
							</div>
							<div class="tva-grading-passing tva-grading-categories-container tva-assessment-no-edit" data-type="category">
								<div class="mr-15 ml-15 mt-15 mb-0 tva-assessment-categories-notice tva-container-notice tva-container-notice-info tva-hide">
									<?php tva_get_svg_icon( 'arrows-1' ); ?>
									<?php echo __( 'Drag grades between sections to change between fail/pass', 'thrive-apprentice' ); ?>
									<span class="tva-container-notice-close click" data-fn="hideTooltip">&times;</span>
								</div>

								<div class="tva-grading-status-container">
									<div class="tva-grading-categories tva-grading-passing-categories"></div>
									<div class="tva-grading-categories-notice tva-grading-passing-notice tva-hide"></div>
								</div>
								<div class="tva-grading-status-container">
									<div class="tva-grading-categories tva-grading-failing-categories"></div>
									<div class="tva-grading-categories-notice tva-grading-fail-notice tva-hide"></div>
								</div>
								<div class="tva-grading-default-categories-select tva-flex tva-align-center tva-space-center mt-5 mb-5">
									<div class="tva-options-drop">
										<div class="tva-options-drop-top">
											<?php tva_get_svg_icon( 'arrow-up-drive' ); ?>
											<span><?php echo __( 'Load a grades preset', 'thrive-apprentice' ); ?></span>
											<?php tva_get_svg_icon( 'caret-down_light' ); ?>
										</div>
										<ul class="tva-options-drop-ul tva-drop-250 tva-drop-top">
											<?php foreach ( Grading_Category::get_default_categories() as $key => $value ): ?>
												<li class="click" data-key="<?php echo $key; ?>" data-fn="loadDefaultCategory"><?php echo $value['label']; ?></li>
											<?php endforeach; ?>
										</ul>
									</div>
								</div>
								<div class="tva-grading-replace-categories-notice tva-hide">
									<div>
										<div>
											<span class="tva-grc-title">
												<?php _e( 'Load preset grades', 'thrive-apprentice' ); ?>
											</span>
											<span class="tva-grc-text">
												<?php _e( 'Are you sure you want to replace the current grades with ', 'thrive-apprentice' ); ?>
												<strong>Academic grades</strong>?
											</span>
										</div>
										<div>
											<button class="tva-empty-btn mr-40 click" data-fn="preventReplaceCategories">
												<?php _e( 'NO, Keep the old grades', 'thrive-apprentice' ); ?>
											</button>
											<button class="tva-empty-btn click" data-fn="allowReplaceCategories">
												<?php _e( 'YES, Load the new grades', 'thrive-apprentice' ); ?>
											</button>
										</div>
									</div>
									<div></div>
								</div>
							</div>
						</div>
						<div class="tva-grading-setting">
							<label for="tva-grading-manually-marked" class="tva-flex tva-align-center">
								<span><?php echo __( 'Manually mark assessment', 'thrive-apprentice' ); ?></span>
								<div class="tva-info-icon tva-relative tva-tooltip-parent ml-5">
									<?php tva_get_svg_icon( 'info-solid' ); ?>
									<div class="tva-custom-tooltip tva-tooltip-modal">
										<p><?php esc_html_e( 'When marking an assessment manually you will review, provide feedback and grade the assessment in the "Assessments inbox”', 'thrive-apprentice' ); ?></p>
									</div>
								</div>
							</label>
							<select id="tva-grading-manually-marked" data-bind="grading_manually_mark">
								<option value="0"><?php echo __( 'No', 'thrive-apprentice' ); ?></option>
								<option value="1"><?php echo __( 'Yes', 'thrive-apprentice' ); ?></option>
							</select>
						</div>
						<div class="tva-container-notice tva-container-notice-orange tva-marked-notice tva-hide mt-10 mb-10" data-type="pass_fail">
							<?php tva_get_svg_icon( 'info-circle_light' ); ?>
							<?php echo __( 'Assessments will be automatically set to "Pass" once a student has submitted their assessment', 'thrive-apprentice' ); ?>
						</div>
						<div class="tva-container-notice tva-container-notice-orange tva-marked-notice tva-hide mt-10 mb-10" data-type="percentage">
							<?php tva_get_svg_icon( 'info-circle_light' ); ?>
							<?php echo __( 'Assessments will be automatically set to the passing percentage once a student has submitted their assessment.', 'thrive-apprentice' ); ?>
						</div>
						<div class="tva-container-notice tva-container-notice-orange tva-marked-notice tva-hide mt-10 mb-10" data-type="score">
							<?php tva_get_svg_icon( 'info-circle_light' ); ?>
							<?php echo __( 'Assessments will be automatically set to the passing score once a student has submitted their assessment.', 'thrive-apprentice' ); ?>
						</div>
						<div class="tva-container-notice tva-container-notice-orange tva-marked-notice tva-hide mt-10 mb-10" data-type="category">
							<?php tva_get_svg_icon( 'info-circle_light' ); ?>
							<?php echo __( 'Assessments will be automatically set to the first passing category once a student has submitted their assessment.', 'thrive-apprentice' ); ?>
						</div>
						<div class="tva-container-notice tva-container-notice-orange tva-marked-notice tva-hide mt-10 mb-10" data-type="category_quiz">
							<?php tva_get_svg_icon( 'info-circle_light' ); ?>
							<?php echo __( 'Assessments will be automatically marked based on the resulting quiz category.', 'thrive-apprentice' ); ?>
						</div>
						<div class="tva-container-notice tva-container-notice-orange tva-marked-notice tva-hide mt-10 mb-10" data-type="score_quiz">
							<?php tva_get_svg_icon( 'info-circle_light' ); ?>
							<?php echo __( 'Assessments will be automatically marked based on the resulting quiz score.', 'thrive-apprentice' ); ?>
						</div>
						<div class="tva-container-notice tva-container-notice-orange tva-marked-notice tva-hide mt-10 mb-10" data-type="percentage_quiz">
							<?php tva_get_svg_icon( 'info-circle_light' ); ?>
							<?php echo __( 'Assessments will be automatically marked based on the resulting quiz percentage.', 'thrive-apprentice' ); ?>
						</div>
					</div>
				</div>
				<div class="tva-tab-content tva-tab-general">
					<div class="tva-details-label mt-15">
						<label class="course-label"><?php echo esc_html__( 'URL', 'thrive-apprentice' ); ?></label>
						<div>
							<label for="tva-assessment-slug"><?php echo get_site_url() . '/assessment/'; ?></label>
							<input id="tva-assessment-slug" class="tva-course-item-slug" data-bind="post_name" type="text" value="<#= model.get('post_name') #>">
							<input type="hidden" value="<?php echo get_site_url() . '/assessment/'; ?><#- model.get('post_name') #>"/>
							<button class="tva-zclip">&nbsp;
								<span class="tva-custom-tooltip"><?php echo esc_attr( __( 'Copy', 'thrive-apprentice' ) ); ?></span>
							</button>
						</div>
					</div>
					<div class="tva-flex tva-align-center mt-30">
						<label class="course-label">
							<?php echo esc_html__( 'Assessment summary', 'thrive-apprentice' ); ?>
						</label>
						<i class="tvd-tooltipped" data-position="top" data-tooltip="<?php echo esc_attr__( 'This will be displayed on the course overview page', 'thrive-apprentice' ); ?>">
							<?php tva_get_svg_icon( 'info-circle_strong' ); ?>
						</i>
					</div>
					<div class="textarea-box">
						<textarea name="tva-assessment-description" id="tva-assessment-description" data-bind="post_excerpt"><#= TVE_Dash.escapeHTML( model.get( 'post_excerpt' ) ) #></textarea>
					</div>
					<div class="tva-flex tva-align-center tva-space-between mt-30 mb-30">
						<span class="tva-details-title">
							<?php echo esc_html__( 'Allow users to comment on this assessment  ', 'thrive-apprentice' ); ?>
						</span>
						<div class="ta-flex-320">
							<select data-bind="comment_status" id="tva-comment-status">
								<option value="closed"><?php echo esc_html__( 'No', 'thrive-apprentice' ); ?></option>
								<option value="open"><?php echo esc_html__( 'Yes', 'thrive-apprentice' ); ?></option>
							</select>
						</div>
					</div>
					<div class="tva-flex tva-align-center tva-space-between mt-30 mb-30">
						<span class="tva-details-title">
							<?php echo esc_html__( 'Give users free access to the assessment?', 'thrive-apprentice' ); ?>
							<div class="tva-info-icon tva-relative tva-tooltip-parent">
								<?php tva_get_svg_icon( 'info-solid' ); ?>
								<div class="tva-custom-tooltip tva-tooltip-modal">
									<p><?php esc_html_e( "Access restrictions are inherited from the parent product.  However, you can override these access restrictions and give users free access to your course content.", 'thrive-apprentice' ); ?></p>
									<p><?php esc_html_e( 'This can be useful, for example, if you have a premium course but want to offer some lessons or modules for free as a teaser.  You’d set the access restrictions for the product, but make specific content free.', 'thrive-apprentice' ); ?></p>
								</div>
							</div>
						</span>
						<div class="ta-flex-320">
							<select data-bind="freemium" id="tva-freemium">
								<option value="inherit"><?php echo esc_html__( 'Inherit access restrictions from product', 'thrive-apprentice' ); ?></option>
								<option value="free-for-logged"><?php echo esc_html__( 'Free for logged in users (require registration)', 'thrive-apprentice' ); ?></option>
							</select>
						</div>
					</div>
					<div id="tva-assessment-options">
						<div id="tva-assessment-upload-options">
							<label class="course-label"><?php echo esc_html__( 'Would you like to add a custom assessment cover image?', 'thrive-apprentice' ); ?></label>
							<div id="tva-assessment-image" class="tva-details-thumb tva-details-cover"></div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="tva-modal-footer-inner pt-10 pb-10 tva-flex tva-space-between">
			<button type="button" class="tva-modal-btn tva-modal-btn-back tva-ai-go-back click" data-fn="goToTypePickup"><?php echo esc_html__( 'Back', 'thrive-apprentice' ); ?></button>
			<button type="button" class="tva-modal-btn tvd-modal-close tva-ai-close tva-hide"><?php echo esc_html__( 'Close', 'thrive-apprentice' ); ?></button>
			<span class="tva-step-marker"><?php echo esc_html__( 'Step 2 of 2', 'thrive-apprentice' ); ?></span>
			<button type="button" class="tva-modal-btn tva-modal-btn-fill-green click tvd-modal-save" data-fn="save"><?php echo esc_html__( 'Save', 'thrive-apprentice' ); ?></button>
		</div>
	</div>
</div>
