<div class="tvd-modal-content">
	<h3 class="tvd-modal-title"><?php esc_html_e( 'Hide this course?', 'thrive-apprentice' ); ?></h3>

	<p><?php esc_html_e( 'Hiding a course will remove it from your publicly accessible course lists. However, it will still be available to customers who have already been granted access to the course. You may still manually or via Automator let new customers access this course.', 'thrive-apprentice' ); ?></p>

</div>
<div class="tva-modal-footer-outer">
	<button type="button" class="tva-modal-btn tvd-modal-close"><?php esc_html_e( 'Cancel', 'thrive-apprentice' ); ?></button>
	<button type="button" class="tva-modal-btn tva-modal-btn-blue click" data-fn="confirm"><?php esc_html_e( 'Yes, hide this course', 'thrive-apprentice' ); ?></button>
</div>
