<div class="tvd-modal-content">
	<h3 class="tvd-modal-title"><?php esc_html_e( 'Archive this course?', 'thrive-apprentice' ); ?></h3>

	<p><?php esc_html_e( 'Archiving a course will remove it from publicly accessible course lists. However, it will still be available to customers who have already been granted access to the course.', 'thrive-apprentice' ); ?></p>

</div>
<div class="tva-modal-footer-outer">
	<button type="button" class="tva-modal-btn tvd-modal-close"><?php esc_html_e( 'Cancel', 'thrive-apprentice' ); ?></button>
	<button type="button" class="tva-modal-btn tva-modal-btn-blue click" data-fn="confirm"><?php esc_html_e( 'Yes, archive this course', 'thrive-apprentice' ); ?></button>
</div>
