<div class="tvd-modal-content">
	<h3 class="tvd-modal-title"><?php esc_html_e( 'Unpublish this course?', 'thrive-apprentice' ); ?></h3>

	<p><?php esc_html_e( 'Unpublishing this course will remove it from your course lists. Customers who have already been granted access will be unable to access the course.', 'thrive-apprentice' ); ?></p>

</div>
<div class="tva-modal-footer-outer">
	<button type="button" class="tva-modal-btn tvd-modal-close"><?php esc_html_e( 'Cancel', 'thrive-apprentice' ); ?></button>
	<button type="button" class="tva-modal-btn tva-modal-btn-blue click" data-fn="confirm"><?php esc_html_e( 'Yes, unpublish this course', 'thrive-apprentice' ); ?></button>
</div>
