<# var style = item.get('video_style'); #>
<# var options = item.get( 'options'); #>
<# var new_question = parseInt( item.get('new_question') ); #>
<div class="tge-video-form tge-video-style-<#= 0 === new_question ? style.selected : TGE_Editor.default_video_style #>">
	<div class="tqb-video-container-responsive">
		<div style="position: relative; padding-top: 56.25%">
			<iframe src="https://iframe.mediadelivery.net/embed/<#= item.get('library_id')#>/<#= item.get('video_id')#>"
					width="551" height="313"
					allow="accelerometer; gyroscope; autoplay; encrypted-media; picture-in-picture"
					loading="lazy"
					allowfullscreen="true"
					style="border: none; position: absolute; top: 0; height: 100%; width: 100%">
			</iframe>
		</div>
	</div>
</div>
</div>
